# Generated by Django 5.0.3 on 2024-06-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_examvenue_feedback_semic_form_examhall_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_attachment',
            field=models.FileField(null=True, upload_to='feedback/attachments/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='specific_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='suggestion_for_improvement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invigilator',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Invigilator/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Student/'),
        ),
    ]
